[build]
publish = "exampleSite/public"

[context.production.environment]
HUGO_VERSION = "0.62.2"

[context.deploy-preview]
command = "hugo -s exampleSite -D -F -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.2"

[context.branch-deploy]
command = "hugo -s exampleSite --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.62.2"


